server:
  # Add /api as a prefix for every request in the server properties
  servlet:
    context-path: /api
  # Set the default port from 8080 to 5000
  port: 5000

app:
  # DataSource Configuration
  datasource:
    jdbc-url: jdbc:postgresql://${URL_DATABASE}
    username: ${STUDENT_SYSTEM_DATABASE_USER}
    password: ${STUDENT_SYSTEM_DATABASE_PASSWORD}
    pool-size: 30